org: igvardo
app: rs-aws-node-be
service: product-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  stage: dev

functions:
  getProductsList:
    handler: handler.getProductsList
    events:
      - http:
          path: /products
          method: get
          cors: true
  getProductsById:
    handler: handler.getProductsById
    events:
      - http:
          path: /products/{productId}
          method: get
          cors: true
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
          exclude: true

plugins:
  - serverless-plugin-typescript
  - serverless-auto-swagger
custom:
  autoswagger:
    apiType: "http"
    swaggerPath: "swagger"
    schemes: ["https"]
    basePath: /${self:provider.stage}
