org: igvardo
app: rs-aws-node-be
service: product-service
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  stage: dev
  environment:
    PGHOST: ${env.PGHOST}
    PGUSER: ${env.PGUSER}
    PGDATABASE: ${env.PGDATABASE}
    PGPASSWORD: ${env.PGPASSWORD}
    PGPORT: ${env.PGPORT}

functions:
  getProductsList:
    handler: handler.getProductsList
    events:
      - http:
          path: /products
          method: get
          cors: true
  getProductsById:
    handler: handler.getProductsById
    events:
      - http:
          path: /products/{productId}
          method: get
          cors: true
  createProduct:
    handler: handler.createProduct
    events:
      - http:
          path: /products
          method: post
          cors: true
          bodyType: CreateProductBody
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
          exclude: true

plugins:
  - serverless-plugin-typescript
  - serverless-auto-swagger
  - serverless-dotenv-plugin

custom:
  autoswagger:
    apiType: "http"
    swaggerPath: "swagger"
    schemes: ["https"]
    basePath: /${self:provider.stage}
