service: authorization-service
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1
  stage: dev

functions:
  basicAuthorizer:
    handler: handler.basicAuthorizer

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
