branch-defaults:
  default:
    environment: null
    group_suffix: null
  task-9:
    environment: igorosa-bff-api-dev
    group_suffix: null
global:
  application_name: igorosa-bff-api
  branch: null
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
