org: igvardo
app: rs-aws-node-be
service: import-service
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  stage: dev
  environment:
    BUCKET: ${env.BUCKET}

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: "s3:ListBucket"
          Resource:
            - "arn:aws:s3:::rs-aws-node-cloud-photos"
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource:
            - "arn:aws:s3:::rs-aws-node-cloud-photos/*"

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: /import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: rs-aws-node-cloud-photos
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
